version: '3.9'

services:

    mysql:
        container_name: 'envidock-mysql'
        image: 'mysql:latest'
        restart: 'always'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
        volumes:
            - 'mysql:/var/lib/mysql'
        ports:
            - '${MYSQL_PORT}:3306'
        networks: 
            - envidock
    
    mongo:
        container_name: 'envidock-mongo'
        image: 'mongo:latest'
        restart: 'always'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_ROOT_INIT_DATABASE}'
        volumes:
            - 'mongo:/data/db'
        ports:
            - '${MONGO_PORT}:27017'
        networks: 
            - envidock
    
    postgres:
        container_name: 'envidock-postgres'
        image: 'postgres:latest'
        restart: 'always'
        environment:
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_DB: '${POSTGRES_DB}'
        volumes:
            - 'postgres:/var/lib/postgresql'
        ports:
            - '${POSTGRES_PORT}:5432'
        networks:
            - envidock

    redis:
        container_name: 'envidock-redis'
        image: 'redis:latest'
        restart: 'always'
        command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
        environment:
            REDIS_PASSWORD: '${REDIS_PASSWORD}'
        volumes:
            - 'redis:/var/lib/redis'
        ports:
            - '${REDIS_PORT}:6379'
        networks:
            - envidock

    rabbitmq:
        container_name: 'envidock-rabbitmq'
        image: 'rabbitmq:management'
        restart: 'always'
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'
        volumes:
            - 'rabbitmq:/var/lib/rabbitmq/'
            - 'rabbitmq-log:/var/log/rabbitmq'
        ports:
            - '${RABBITMQ_PORT}:5672'
            - '${RABBITMQ_MANAGEMENT_PORT}:15672'
        networks:
            - envidock

volumes:
    mysql:
    mongo:
    postgres:
    redis:
    rabbitmq:
    rabbitmq-log:

networks:
    envidock:
